local_controller:
  ros__parameters:
    lookahead_distance: 2.0
    steering_gain: .5
    stationary_turn_angle: .4
    simulate_turtlebot: True #change to false for running on excavator
    odom_topic: 'odom' #change to 'odom' for simulation, 'gps_pose' for excavator